name: szarp-terminal
version: "9999"
summary: SZARP Terminal application
description: SZARP is Linux SCADA software - system for data acquisition, archiving and raporting.
confinement: strict


apps:
  draw3:
    command: opt/szarp/bin/draw3
    plugs: [x11, unity7]
  szrsync:
    plugs: [network, network-bind]
    command: opt/szarp/bin/szrsync
parts:
  szarp-terminal:
    plugin: autotools
    source: .
    stage-packages:
      - cpp
      - cpp-5
      - dbus
      - fontconfig
      - fontconfig-config
      - fonts-dejavu-core
      - fonts-freefont-ttf
      - hicolor-icon-theme
      - libatk1.0-0
      - libatk1.0-data
      - libauthen-sasl-perl
      - libavahi-client3
      - libavahi-common-data
      - libavahi-common3
      - libboost-date-time1.58.0
      - libboost-filesystem1.58.0
      - libboost-locale1.58.0
      - libboost-system1.58.0
      - libboost-thread1.58.0
      - libc-ares2
      - libcairo2
      - libcap-ng0
      - libcups2
      - libcurl3
      - libdatrie1
      - libdbus-1-3
      - libdrm-amdgpu1
      - libdrm-intel1
      - libdrm-nouveau2
      - libdrm-radeon1
      - libdrm2
      - libelf1
      - libencode-locale-perl
      - libfile-basedir-perl
      - libfile-desktopentry-perl
      - libfile-listing-perl
      - libfile-mimeinfo-perl
      - libfont-afm-perl
      - libfontconfig1
      - libfontenc1
      - libfreetype6
      - libftgl2
      - libgdk-pixbuf2.0-0
      - libgdk-pixbuf2.0-common
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglapi-mesa
      - libglib2.0-0
      - libglib2.0-data
      - libglu1-mesa
      - libgraphite2-3
      - libgtk2.0-0
      - libgtk2.0-bin
      - libgtk2.0-common
      - libharfbuzz0b
      - libhtml-form-perl
      - libhtml-format-perl
      - libhtml-parser-perl
      - libhtml-tagset-perl
      - libhtml-tree-perl
      - libhttp-cookies-perl
      - libhttp-daemon-perl
      - libhttp-date-perl
      - libhttp-message-perl
      - libhttp-negotiate-perl
      - libice6
      - libio-html-perl
      - libio-socket-ssl-perl
      - libipc-system-simple-perl
      - libisl15
      - libjbig0
      - libjpeg-turbo8
      - libjpeg8
      - libllvm3.8
      - libluajit-5.1-2
      - libluajit-5.1-common
      - liblwp-mediatypes-perl
      - liblwp-protocol-https-perl
      - libmailtools-perl
      - libmpc3
      - libmpfr4
      - libnet-dbus-perl
      - libnet-http-perl
      - libnet-smtp-ssl-perl
      - libnet-ssleay-perl
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpciaccess0
      - libpgm-5.2-0
      - libpixman-1-0
      - libprotobuf9v5
      - libquadmath0
      - librsync1
      - libsm6
      - libthai-data
      - libthai0
      - libtie-ixhash-perl
      - libtiff5
      - libtimedate-perl
      - libtxc-dxtn-s2tc0
      - liburi-perl
      - libwrap0
      - libwww-perl
      - libwww-robotrules-perl
      - libwxbase2.8-0
      - libwxgtk2.8-0
      - libx11-protocol-perl
      - libx11-xcb1
      - libxaw7
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-glx0
      - libxcb-present0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxfixes3
      - libxft2
      - libxi6
      - libxinerama1
      - libxml-parser-perl
      - libxml-twig-perl
      - libxml-xpathengine-perl
      - libxmlrpc-epi0
      - libxmu6
      - libxpm4
      - libxrandr2
      - libxrender1
      - libxshmfence1
      - libxt6
      - libxtst6
      - libxv1
      - libxxf86dga1
      - libxxf86vm1
      - libzip4
      - libzmq1
      - openssh-server
      - openssh-sftp-server
      - shared-mime-info
      - ssh-import-id
      - sshpass
      - szarp-base
      - szarp-doc-html
      - szarp-terminal
      - szarp-wx
      - tcpd
      - ttf-freefont
      - unzip
      - x11-common
      - x11-utils
      - x11-xserver-utils
      - xdg-user-dirs
      - xdg-utils
      - zip
